# Generated by Django 3.0.8 on 2020-08-04 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200731_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='follower',
            field=models.ManyToManyField(related_name='to_follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
